### PR TITLE
Prepare v1.5.0 release

### PR DESCRIPTION
**Pull request by mauricerkelly**

### CODE REVIEW

**Comment by mauricerkelly** [comment]
@Arcanemagus anything I've missed from the release preparation?

**Comment by Arcanemagus** [comment]
Depends on how you are planning on releasing this. You can only commit the changelog part, then do `apm publish minor` to let it do the `package.json` update, tag a new version, push it up to github, then notify the APM repo that there is a new version.

Alternatively you can merge this PR, create a tag manually from the new state of `master`, then run `apm publish --tag <tag name>`, allowing you full control over the state of the repo.

[This](https://gist.github.com/Arcanemagus/d068e3f990ca4b38fa69a1425e3a76fd#file-apm-publish-ps1-L36-L39) is how I currently publish releases, mainly because I sign all the commits which you can't do if you are using `apm` to bump the version, but the first method is the easiest (update changelog, then just do `apm publish minor`).

**Comment by mauricerkelly** [comment]
I'll see if I'm able to sign the commits (are you on Keybase, btw?) and if so, I'll redo this trying to follow how you do it.

**Comment by mauricerkelly** [comment]
This PR is now redundant as the release has been prepped and push directly.

**Pull request closed without merging**
